.Dd July 28, 2022
.Dt fsntfsinfo
.Os libfsntfs
.Sh NAME
.Nm fsntfsinfo
.Nd determines information about a Windows NT File System (NTFS) volume
.Sh SYNOPSIS
.Nm fsntfsinfo
.Op Fl B Ar bodyfile
.Op Fl E Ar mft_entry_index
.Op Fl F Ar file_entry
.Op Fl o Ar offset
.Op Fl dhHUvV
.Ar source
.Sh DESCRIPTION
.Nm fsntfsinfo
is a utility to determine information about a Windows NT File System (NTFS) volume
.Pp
.Nm fsntfsinfo
is part of the
.Nm libfsntfs
package.
.Nm libfsntfs
is a library to access the Windows NT File System (NTFS) format
.Pp
.Ar source
is the source file.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl B Ar bodyfile
output file system hierarchy as a bodyfile
.It Fl d
calculate a MD5 hash of a file entry to include in the bodyfile
.It Fl E Ar mft_entry_index
show information about a specific MFT entry index or "all"
.It Fl F Ar file_entry
show information about a specific file entry path
.It Fl h
shows this help
.It Fl H
shows the file system hierarcy
.It Fl o Ar offset
specify the volume offset
.It Fl U
shows information from the USN change journal ($UsnJrnl)
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# fsntfsinfo ntfs-img-kw-1.dd
fsntfsinfo 20160414
.sp
Windows NT File System information:
.sp
Volume information:
	Name				: KW-SRCH-1
	Version				: 3.1
	Serial number			: ba50ed9250ed5623
	Cluster block size		: 512
	MFT entry size			: 1024
	Index entry size		: 4096
.sp
.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh BUGS
Please report bugs of any kind to <joachim.metz@gmail.com> or on the project website:
https://github.com/libyal/libfsntfs/
.Sh AUTHOR
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
Copyright 2010-2022, Joachim Metz <joachim.metz@gmail.com>.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
