.Dd May 29, 2014
.Dt libfsntf 3
.Os libfsntf
.Sh NAME
.Nm libfsntf.h
.Nd Library to access the Windows NT File System (NTFS) format
.Sh LIBRARY
.Lb libfsntf
.Sh SYNOPSIS
.In libfsntf.h
.Pp
Support functions
.Ft const char *
.Fn libfsntf_get_version "void"
.Ft int
.Fn libfsntf_check_volume_signature "const char *filename, libfsntf_error_t **error"
.Pp
Available when compiled with wide character string support:
.Ft int
.Fn libfsntf_check_volume_signature_wide "const wchar_t *filename, libfsntf_error_t **error"
.Pp
Available when compiled with libbfio support:
.Ft int
.Fn libfsntf_check_volume_signature_file_io_handle "libbfio_handle_t *file_io_handle, libfsntf_error_t **error"
.Pp
Notify functions
.Ft void
.Fn libfsntf_notify_set_verbose "int verbose"
.Ft int
.Fn libfsntf_notify_set_stream "FILE *stream, libfsntf_error_t **error"
.Ft int
.Fn libfsntf_notify_stream_open "const char *filename, libfsntf_error_t **error"
.Ft int
.Fn libfsntf_notify_stream_close "libfsntf_error_t **error"
.Pp
Error functions
.Ft void 
.Fn libfsntf_error_free "libfsntf_error_t **error"
.Ft int
.Fn libfsntf_error_fprint "libfsntf_error_t *error, FILE *stream"
.Ft int
.Fn libfsntf_error_sprint "libfsntf_error_t *error, char *string, size_t size"
.Ft int 
.Fn libfsntf_error_backtrace_fprint "libfsntf_error_t *error, FILE *stream"
.Ft int
.Fn libfsntf_error_backtrace_sprint "libfsntf_error_t *error, char *string, size_t size"
.Pp
Volume functions
.Sh DESCRIPTION
The
.Fn libfsntf_get_version
function is used to retrieve the library version.
.Sh RETURN VALUES
Most of the functions return NULL or -1 on error, dependent on the return type. For the actual return values refer to libfsntf.h
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh NOTES
.Sh BUGS
Please report bugs of any kind to <joachim.metz@gmail.com> or on the project website:
https://github.com/libyal/libfsntfs/
.Sh AUTHOR
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
Copyright 2010-2014, Joachim Metz <joachim.metz@gmail.com>.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
the libfsntf.h include file
